.TH DSBLOCKS 1 dsblocks\-VERSION
.SH NAME
dsblocks \- dwm status blocks
.SH SYNOPSIS
.B dsblocks
.RB [ \-d
.IR debug ]
.SH DESCRIPTION
.B dsblocks
is a simple status blocks for dwm.
.SH OPTIONS
.TP
.B \-d
print result on screen.
.SH USAGE
put dsblocks command in your
.IR \.xinitrc
.SH SEE ALSO
.IR dwm (1)
